#include "code.h"
#include <stdio.h>
#include <stdlib.h>
#include "object.h"

void codeop_debug(enum CodeOpKind k)
{
	switch(k) {
	#define BOILERPLATE(KIND) case KIND: puts(#KIND); break;
		BOILERPLATE(CODE_CONSTANT)
		BOILERPLATE(CODE_SETATTR)
		BOILERPLATE(CODE_GETATTR)
		BOILERPLATE(CODE_CREATEBOX)
		BOILERPLATE(CODE_SET2BOX)
		BOILERPLATE(CODE_UNBOX)
		BOILERPLATE(CODE_CALLCODEFUNC)
		BOILERPLATE(CODE_CALLBUILTINFUNC)
		BOILERPLATE(CODE_JUMP)
		BOILERPLATE(CODE_JUMPIF)
		BOILERPLATE(CODE_JUMPIFEQ_INT)
		BOILERPLATE(CODE_JUMPIFEQ_STR)
		BOILERPLATE(CODE_STRJOIN)
		BOILERPLATE(CODE_THROW)
		BOILERPLATE(CODE_SETMETHODS2CLASS)
		BOILERPLATE(CODE_POP1)
		BOILERPLATE(CODE_RETURN)
		BOILERPLATE(CODE_INT_ADD)
		BOILERPLATE(CODE_INT_SUB)
		BOILERPLATE(CODE_INT_MUL)
		BOILERPLATE(CODE_FUNCBEGINS)
		BOILERPLATE(CODE_INT_NEG)
	#undef BOILERPLATE
	}
}

void codeop_destroy(struct CodeOp op)
{
	if (op.kind == CODE_CONSTANT)
		OBJECT_DECREF(op.data.obj);
}
